### ISSUE TITLE
Email Address not verified

### ISSUE THREAD

**Issue by mrjonny2** [sirceljm/AWS-SES-simple-mail-forward#1]
I am getting an error when it comes to forwarding.
MessageRejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: <Email address that sent the email>
Any ideas? I am new to lambda so not too sure how to debug it

**Comment by mtso** [comment]
AWS SES starts you off in a sandbox, and within the sandbox, one can only send emails to email addresses that are verified.

**Comment by humeniukd** [comment]
Please use AWS [guide](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html) to move your account out of the sandbox

**Comment by sjlu** [comment]
This is actually because emails coming in from SES have the a FROM header attached to it. Sending email with that raw header fails as its not verified under your SES account.

Added in pull request #2 to address those issues

**Comment by sirceljm** [comment]
Thank you for your contribution! I merged your pull request.
